inherit_gem:
  rubocul: rubocul_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.3.5
  TargetRailsVersion: 8.0.2
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/**/*'

Layout/LineLength:
  Exclude:
    - 'lib/tasks/bibdata/ci.rake'

Metrics/AbcSize:
  Exclude:
    - 'lib/bibdata/fixture_helper.rb'
    - 'lib/bibdata/folio_api_client.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/bibdata/scsb.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/bibdata/scsb.rb'
    - 'spec/requests/barcode_spec.rb'

