name: CI

on:
  push:
    branches: ['**']

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager
  ci:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.5'
    env:
      RAILS_ENV: test

    steps:
      - name: Install libxslt for nokogiri gem (required for ruby platform build)
        run: sudo apt-get install -y libxml2-dev libxslt-dev
      - uses: actions/checkout@v5
      - name: Add --no-document option to .gemrc file to speed up bundle install
        run: "echo 'gem: --no-document' > ~/.gemrc"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Copy config files
        run: bin/copy-config-template-files
      - name: Run CI task
        run: bundle exec rake bibdata:ci
